const data = {
    course: [
      {
        _id: "1",
        image: "https://img-c.udemycdn.com/course/240x135/567828_67d0.jpg",
        name: "2021 Complete Python Bootcamp From Zero to Hero in Python",
        createdBy: "Jose Portilla",
        rating: 4.6,
        numReviews: 888,
        price: "455",
        videos: 41,
        time: 8,
        studentEndroll: 10947,
      },
      {
        _id: "2",
        image: "https://img-c.udemycdn.com/course/240x135/950390_270f_3.jpg",
        name: "Machine Learning A-Z™: Hands-On Python & R In Data Science",
        createdBy: "Kirill Eremenko",
        rating: 4.5,
        numReviews: 754,
        price: "455",
        videos: 99,
        time: 14,
        studentEndroll: 4134,
      },
      {
        _id: "3",
        image: "https://img-c.udemycdn.com/course/240x135/903744_8eb2.jpg",
        name: "Python for Data Science and Machine Learning Bootcamp",
        createdBy: "Jose Portilla",
        rating: 4.6,
        numReviews: 658,
        price: "455",
        videos: 19,
        time: 4,
        studentEndroll: 2321,
      },
      {
        _id: "4",
        image: "https://img-c.udemycdn.com/course/240x135/629302_8a2d_2.jpg",
        name: "Learn Python Programming Masterclass",
        createdBy: "Tim Buchalka",
        rating: 4.2,
        numReviews: 978,
        price: "455",
        videos: 40,
        time: 16,
        studentEndroll: 2816,
      },
      {
        _id: "5",
        image: "https://img-c.udemycdn.com/course/240x135/692188_9da7_21.jpg",
        name: "The Python Mega Course: Build 10 Real World Applications",
        createdBy: "Ardit Sulce",
        rating: 4.3,
        numReviews: 599,
        price: "455",
        videos: 70,
        time: 13,
        studentEndroll: 2107,
      },
      {
        _id: "6",
        image: "https://img-c.udemycdn.com/course/240x135/396876_cc92_7.jpg",
        name: "Learning Python for Data Analysis and Visualization",
        createdBy: "Jose Portilla",
        rating: 4.4,
        numReviews: 158,
        price: "455",
        videos: 84,
        time: 13,
        studentEndroll: 1471,
      },
      {
        _id: "7",
        image: "https://img-c.udemycdn.com/course/240x135/2776760_f176_5.jpg",
        name: "100 Days of Code - The Complete Python Pro Bootcamp for 2021",
        createdBy: "Dr. Angela Yu",
        rating: 4.2,
        numReviews: 177,
        price: "455",
        videos: 50,
        time: 9,
        studentEndroll: 2885,
      },
      {
        _id: "8",
        image: "https://img-c.udemycdn.com/course/240x135/1362070_b9a1_2.jpg",
        name: "React - The Complete Guide (incl Hooks, React Router, Redux)",
        createdBy: "Maxi milian",
        rating: 4.5,
        numReviews: 777,
        price: "455",
        videos: 49,
        time: 6,
        studentEndroll: 3564,
      },
      {
        _id: "9",
        image: "https://img-c.udemycdn.com/course/240x135/1565838_e54e_12.jpg",
        name: "The Complete JavaScript Course 2021: From Zero to Expert!",
        createdBy: "Jonas Schme",
        rating: 4.7,
        numReviews: 656,
        price: "455",
        videos: 42,
        time: 6,
        studentEndroll: 4710,
      },
    ],
  };
  
  export default data;